server:
  port: 8080

api:
  version: 1.0.0
  title: CQRS Java 01
  description: CQRS Java 01

spring:
  profiles:
    active: development
---

spring:
  application:
    name: cqrs-java-01
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    h2:
      console:
        enabled: true
        path: /h2-console
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    title: CQRS Java 01
    version: 1.0.0
    description: CQRS Java 01
    license: Apache License Version 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    termsOfServiceUrl: http://localhost:8080/v1/api/swagger-ui.html

