server:
  port: 8080
  servlet:
    context-path: /v1/api

api:
  version: 1.0.0
  title: CQRS Java 01
  description: CQRS Java 01

spring:
  application:
    name: cqrs-java-01
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

springdoc:
  api-docs:
    enabled: true # Habilita a geração da documentação
    path: /v1/api-docs # Caminho onde o OpenAPI estará disponível
  swagger-ui:
    enabled: true # Habilita a interface do Swagger UI
    path: /swagger-ui.html # Caminho para acessar o Swagger UI
